# if you want use english type en, 한국어를 사용하고 싶으시면 kr을 적어주세요.

Language: en
checkUpdates: true

# Set the permission. if you want everyone to use it, write enable, or you don't want use it everyone write disable, If you want to use OP user only, please write false.
# 퍼미션을 설정합니다. 기본적으로 모두 사용하게 하고싶으면 enable를 적어주시고 아무도 사용하지 못하게 하려면 disable, OP유저만 사용하게 하고싶으면 false를 적어주세요.

# Use or disable the portal.
# 포탈 사용을 허용하거나 허용하지 않습니다.
useportal: enable

# Use or disable the scroll.
# 스크롤 사용을 허용하거나 허용하지 않습니다.
usescroll: enable

# Goto command allows or disables direct movement to the warp.
# Goto 명령어로 워프로 직접 이동하는것을 허용하거나 허용하지 않습니다.
goto: op

# allows or disables portal create, or removing.
# 포탈을 만들거나 지우는것을 허용하거나 허용하지 않습니다.
portal: op

# allows or disables make Scroll.
# 스크롤 제작을 허용하거나 허용하지 않습니다.
scroll: op

# allows or disables warp see warp list, create, or removing.
# 워프를 만들고, 지우로, 워프 리스트를 보는것을 허용하거나 허용하지 않습니다.
warp: op

# You can grant permissions to other users. I recommend you not to allow it.
# 다른 플레이어에게 퍼미션 권한을 부여하는것을 허용하거나 허용하지 않습니다. 이 퍼미션은 허용하지 않는것을 추천합니다.
give: op