name: FWarp
main: com.dalyeou.fwarp.FWarpMain
version: 1.0

commands:
  Portal:
    description: Create, Delete portal.
  Warp:
    description: Reload, Create, Delete warp. And Show Warp List.
  Scroll:
    description: Make warp portal scroll.
  Goto:
    description: direct movement to the warp.
  SetPer:
    description: You can grant permissions to other users..
  Language:
    description: Set plugin's Language.
    
permissions:
  warp.portal:
    default: op
  warp.portal.use:
    default: true
  warp.warp:
    default: op
  warp.scroll:
    default: op
  warp.scroll.use:
    default: true
  warp.goto:
    default: op
  warp.give:
    default: op
  warp.Language:
    default: op